services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt_server/config:/mosquitto/config
      - ./mqtt_server/data:/mosquitto/data
      - ./mqtt_server/log:/mosquitto/log
